[project]
name = "vanguard-ingestion-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.2.0",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "pyspark==3.5.4",
    "setuptools>=82.0.1",
    "langgraph>=0.1.23",
    "langchain-google-genai>=0.1.1",
    "langchain-core>=0.4.27",
    "pydantic>=2.10.5"
]